# baseURL = 'http://127.0.0.1:5500/public' ## for local live server
baseURL = 'https://iambaangkok.github.io/me' ## for deploy to github pages at /docs
languageCode = 'en-us'
title = 'iambaangkok.me | portfolio'
theme = 'typo'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[taxonomies]
tag = 'tags'

[params]
# Meta description
description = "bk's portfolio"

# Appearance settings
theme = 'light'
colorPalette = 'base16-eighties'
hideHeader = false

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
iambaangkok is an ambitious programmer with a passion for creating great games.
At **day**, I work as a backend software engineer.
At **night**, I make games and boardgames, or learn about cool stuff, like shaders! (my current study).
"""

# Collection to display on home
homeCollectionTitle = 'My Games / Boardgames / etc.'
homeCollection = 'my-games'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'
listShowTags = true

# Breadcrumbs
[params.breadcrumbs]
enabled = true
showCurrentPage = true
home = "/me"

# Social icons
[[params.social]]
name = "x"
url = "https://x.com/meisbk"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/iambaangkok/"

[[params.social]]
name = "github"
url = "https://github.com/iambaangkok"

# Main menu pages
[[params.menu]]
name = "me"
url = ""

[[params.menu]]
name = "my-games"
url = "my-games"

[[params.menu]]
name = "boardgames"
url = "boardgames"

[[params.menu]]
name = "shaders"
url = "shaders"

[[params.menu]]
name = "contacts"
url = "contacts"

# Syntax highlight on code blocks
[markup]
[markup.highlight]
style = 'onedark'

[markup.goldmark.renderer]
unsafe = true

# Giscus comments
# [params.giscus]
# enable = false
# repo = "user/repo"
# repoid = "repoId"
# category = "General"
# categoryid = "categoryId"
# mapping = "pathname"
# theme = "preferred_color_scheme"
